### ISSUE TITLE
Авторизация при любых данных.

### ISSUE THREAD

**Issue by sinneren** [maxfarseer/tutorial-tz-1-hooks-typescript#1]
Допустим пользователь на странице авторизации и не авторизован
И в инпуты передаются рандомные данные, отличные от Admin и 12345.
Когда пользователь нажал Login
То отобразилась ошибка входа
Когда пользователь обновил страницу
То отображена кнопка выйти
И на странице профиля виден текст "Профиль"

Возможно, потому что в auth.ts нужно было делать else в if (!checkCredentials(data)) или делать return;

**Comment by sinneren** [comment]
Пофиксил: https://github.com/maxfarseer/tutorial-tz-1-hooks-typescript/pull/2

**Comment by maxfarseer** [comment]
Спасибо, принято!
